ENV["RELEASE_NOTES_PATH"] = "./release-notes.txt"
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

# iOS Paths
ENV["IOS_BUILD_PATH"] = "./builds/ios"
ENV["IPA_PATH"] = "./builds/ios/WBoilerplate.ipa"
ENV["POD_FILE_PATH"] = "./ios/Podfile"
ENV["IOS_PROJ_PATH"] = "./ios/WBoilerplate.xcodeproj"
ENV["IOS_WORKSPACE_PATH"] = "./ios/WBoilerplate.xcworkspace"
ENV["IOS_SCHEME_NAME"] = "WBoilerplate"
ENV["IOS_OUTPUT_NAME"] = "WBoilerplate.ipa"
ENV["IOS_BUILD_CONFIGURATION"] = "Release"
ENV["IOS_DERIVED_DATA_PATH"] = "./ios/DerivedData"

# Android Paths
ENV["ANDROID_PROJECT_PATH"] = "android/"
ENV["ANDROID_BUILD_PATH"] = "./builds/android"
ENV["APK_PATH"] = "./builds/android/app-release.apk"
ENV["AAB_PATH"] = "./builds/android/app-release.aab"

# Slack configs
ENV["SLACK_WEB_HOOK"] = "https://hooks.slack.com/services/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"
# ENV["APP_ICON_URL"] = "https://firebasestorage.googleapis.com/v0/b/sigortam-cepte-v2.appspot.com/o/app-icon%2Ficon.png?alt=media&token=8709cab0-0bc4-48ac-b585-851bee325d04"
ENV["SLACK_USER_NAME"] = "Wunder Build Machine"
ENV["GENERAL_PROJECT_MESSAGE"] = "New test package of WBoilerplate is live!"
ENV["EXCEPTION_PROJECT_MESSAGE"] = "Test package build exception!"

platform :ios do
  lane :beta do
    ios_derived_data_path = File.expand_path(ENV["IOS_DERIVED_DATA_PATH"])
    cache_folder = File.expand_path("#{ios_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/#{ENV["IOS_SCHEME_NAME"]}/BuildProductsPath/#{ENV["IOS_BUILD_CONFIGURATION"]}-iphoneos")
    cocoapods(
      podfile: ENV["POD_FILE_PATH"],
      use_bundle_exec: "false",
    )
    update_code_signing_settings(
      use_automatic_signing: true,
      path: ENV["IOS_PROJ_PATH"],
    )

    if (File.exist?(cache_folder))
      fastlane_require "xcodeproj"
      project = Xcodeproj::Project.open(ENV["IOS_PROJ_PATH"])
      target = project.targets.select { |target| target.name == ENV["IOS_SCHEME_NAME"] }.first
      phase = target.shell_script_build_phases.select { |phase| phase.name && phase.name.include?("Copy Pods Resources") }.first
      if (!phase.shell_script.start_with?("BUILT_PRODUCTS_DIR"))
        phase.shell_script = "BUILT_PRODUCTS_DIR=#{cache_folder} #{phase.shell_script}"
        project.save()
      end
      gym(
        scheme: ENV["IOS_SCHEME_NAME"],
        clean: false,
        project: ENV["IOS_PROJ_PATH"],
        export_method: "ad-hoc",
        output_directory: ENV["IOS_BUILD_PATH"],
        xcargs: "-allowProvisioningUpdates",
        output_name: ENV["IOS_OUTPUT_NAME"],
        export_options: {
          compileBitcode: false,
          uploadBitcode: false,
          uploadSymbols: false,
        },
        xcargs: [
          "PODS_CONFIGURATION_BUILD_DIR=#{cache_folder}",
          "FRAMEWORK_SEARCH_PATHS='#{cache_folder} $(inherited)'",
          "LIBRARY_SEARCH_PATHS='#{cache_folder} $(inherited)'",
          "SWIFT_INCLUDE_PATHS=#{cache_folder}",
        ].join(" "),
      )
    else
      gym(
        scheme: ENV["IOS_SCHEME_NAME"],
        clean: true,
        workspace: ENV["IOS_WORKSPACE_PATH"],
        export_method: "ad-hoc",
        output_directory: ENV["IOS_BUILD_PATH"],
        xcargs: "-allowProvisioningUpdates",
        output_name: ENV["IOS_OUTPUT_NAME"],
      )
      require "fileutils"
      dirs = [
        File.expand_path("#{ios_derived_data_path}/info.plist"),
        File.expand_path("#{ios_derived_data_path}/Logs"),
        File.expand_path("#{ios_derived_data_path}/SourcePackages"),
        File.expand_path("#{ios_derived_data_path}/ModuleCache.noindex"),
        File.expand_path("#{ios_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/MyApp.build"),
        File.expand_path("#{ios_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/XCBuildData"),
        File.expand_path("#{ios_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/SwiftSupport"),
        File.expand_path("#{ios_derived_data_path}/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/PrecompiledHeaders"),
      ]
      dirs.each { |dir| FileUtils.rm_rf(dir) }
    end
  end
end

platform :android do
  lane :beta do
    gradle(task: "clean", project_dir: ENV["ANDROID_PROJECT_PATH"])
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: ENV["ANDROID_PROJECT_PATH"],
    )
    create_builds
    create_dir
    sh "cp ../android/app/build/outputs/apk/release/app-release.apk ../builds/android/"
  end
end

lane :create_builds do
  begin
    sh "mkdir ../builds"
  rescue => ex
    UI.error(ex)
  end
end

lane :create_dir do
  begin
    sh "mkdir ../builds/android"
  rescue => ex
    UI.error(ex)
  end
end

lane :commit_push do
  sh "yarn afterRelease"
end

lane :firebase_result do
  slack(
    username: ENV["SLACK_USER_NAME"],
    message: ENV["GENERAL_PROJECT_MESSAGE"],
    success: true,
    slack_url: ENV["SLACK_WEB_HOOK"],
    default_payloads: [:last_git_commit],
    attachment_properties: {
      thumb_url: ENV["APP_ICON_URL"],
      fields: [
        {
          title: "Build Date",
          value: Time.new.to_s,
          short: true,
        },
        {
          title: "Build by",
          value: "Fastlane",
          short: true,
        },
        {
          title: "Release Notes",
          value: File.read("../release-notes.txt"),
          short: false,
        },
      ],
    },
  )
end

error do |lane, exception|
  slack(
    username: ENV["EXCEPTION_PROJECT_MESSAGE"],
    message: ENV["EXCEPTION_PROJECT_MESSAGE"],
    success: false,
    slack_url: ENV["SLACK_WEB_HOOK"],
    default_payloads: [:lane],
    attachment_properties: {
      thumb_url: ENV["APP_ICON_URL"],
      fields: [
        {
          title: "Exception",
          value: exception,
          short: true,
        },
      ],
    },
  )
end
