name: Wunder Boilerplate CI - Send To Firebase App Distribution
on:
  workflow_call:

jobs:
  build-ios:
    name: Buid iOS Binary
    runs-on: self-hosted
    steps:
      - name: Buid iOS Binary
        run: fastlane ios beta
  
  build-android:
    name: Buid Android Binary
    runs-on: self-hosted
    steps:
      - name: Buid Android Binary
        run: fastlane android beta
    
    needs: [build-ios]
