name: CI - npm release
on:
  push:
    branches: [master]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'chore: release')"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.15.1
          check-latest: true
          registry-url: https://registry.npmjs.com/
          scope: '@thisiswunder'
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install Yarn
        run: npm install -g yarn
      - run: git config user.email "${{secrets.GIT_CONFIG_EMAIL}}"
      - run: git config user.name "${{secrets.GIT_CONFIG_DEV_NAME}}"
      - run: yarn
      - run: yarn release-it
