name: CI - npm release
on:
  push:
    branches: [master]

jobs:
  release-it:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'chore: release')"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.15.1
          check-latest: true
          registry-url: https://registry.npmjs.com/
          scope: '@thisiswunder'
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install Yarn to global
        run: npm install -g yarn

      - name: Add email & name to git config
        run: git config user.email "${{secrets.GIT_CONFIG_EMAIL}}" && git config user.name "${{secrets.GIT_CONFIG_DEV_NAME}}"

      - name: Install packages
        run: yarn

      - name: Create release
        run: GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} yarn release-it
